/**
 * withAndroidReleaseSigning
 *
 * The Expo bare template ships `android/app/build.gradle` with the release
 * build type signed by `signingConfigs.debug`:
 *
 *     release {
 *         // Caution! In production, you need to generate your own keystore file.
 *         // see https://reactnative.dev/docs/signed-apk-android.
 *         signingConfig signingConfigs.debug
 *
 * Google Play rejects a debug-signed AAB ("You uploaded an APK or Android App
 * Bundle that was signed in debug mode"). Because `android/` is regenerated by
 * `expo prebuild` and is not committed, that line cannot simply be hand-edited
 * once - it has to be patched every time the native project is generated, which
 * is what this config plugin does.
 *
 * The keystore itself is never stored in the repo. Supply it as Gradle
 * properties, either in `~/.gradle/gradle.properties` (recommended - outside the
 * project, never committed) or on the command line:
 *
 *     ./gradlew :app:bundleRelease \
 *       -PZBR_UPLOAD_STORE_FILE=/absolute/path/to/zbr-upload.keystore \
 *       -PZBR_UPLOAD_STORE_PASSWORD=... \
 *       -PZBR_UPLOAD_KEY_ALIAS=zbr-upload \
 *       -PZBR_UPLOAD_KEY_PASSWORD=...
 *
 * When those properties are absent the release build falls back to the debug
 * keystore so that a local smoke-test build still works, and prints a loud
 * warning. Never upload the output of such a build.
 */

const { withAppBuildGradle } = require('expo/config-plugins');

const SIGNING_CONFIGS_ANCHOR = 'signingConfigs {';

const RELEASE_SIGNING_CONFIG = `
        release {
            if (project.hasProperty('ZBR_UPLOAD_STORE_FILE')) {
                storeFile file(ZBR_UPLOAD_STORE_FILE)
                storePassword ZBR_UPLOAD_STORE_PASSWORD
                keyAlias ZBR_UPLOAD_KEY_ALIAS
                keyPassword ZBR_UPLOAD_KEY_PASSWORD
            } else {
                logger.warn('[ZBR] ZBR_UPLOAD_STORE_FILE is not set - the release build will be signed with the DEBUG keystore. Google Play will reject this artifact.')
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }`;

// The exact lines the bare template emits for the release build type.
const TEMPLATE_RELEASE_SIGNING = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const PATCHED_RELEASE_SIGNING = `            // Signed by withAndroidReleaseSigning: reads ZBR_UPLOAD_* Gradle properties.
            signingConfig signingConfigs.release`;

/** @type {import('expo/config-plugins').ConfigPlugin} */
const withAndroidReleaseSigning = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `withAndroidReleaseSigning expected a Groovy build.gradle, got "${cfg.modResults.language}".`
      );
    }

    let contents = cfg.modResults.contents;

    if (contents.includes('signingConfigs.release')) {
      // Already patched (e.g. prebuild ran twice without --clean).
      return cfg;
    }

    const anchorIndex = contents.indexOf(SIGNING_CONFIGS_ANCHOR);
    if (anchorIndex === -1) {
      throw new Error(
        `withAndroidReleaseSigning could not find "${SIGNING_CONFIGS_ANCHOR}" in android/app/build.gradle. ` +
          'The Expo template changed - update this plugin before releasing, or the AAB will be debug-signed.'
      );
    }

    const insertAt = anchorIndex + SIGNING_CONFIGS_ANCHOR.length;
    contents = contents.slice(0, insertAt) + RELEASE_SIGNING_CONFIG + contents.slice(insertAt);

    if (!contents.includes(TEMPLATE_RELEASE_SIGNING)) {
      throw new Error(
        'withAndroidReleaseSigning could not find the template release signingConfig line in ' +
          'android/app/build.gradle. The Expo template changed - update this plugin before ' +
          'releasing, or the AAB will be debug-signed.'
      );
    }
    contents = contents.replace(TEMPLATE_RELEASE_SIGNING, PATCHED_RELEASE_SIGNING);

    cfg.modResults.contents = contents;
    return cfg;
  });

module.exports = withAndroidReleaseSigning;
