/**
 * withAndroidReleaseSigning
 *
 * The Expo bare template ships `android/app/build.gradle` with the release
 * build type signed by `signingConfigs.debug`:
 *
 *     release {
 *         // Caution! In production, you need to generate your own keystore file.
 *         // see https://reactnative.dev/docs/signed-apk-android.
 *         signingConfig signingConfigs.debug
 *
 * Google Play rejects a debug-signed AAB ("You uploaded an APK or Android App
 * Bundle that was signed in debug mode"). Because `android/` is regenerated by
 * `expo prebuild` and is not committed, that line cannot simply be hand-edited
 * once - it has to be patched every time the native project is generated, which
 * is what this config plugin does.
 *
 * The keystore itself is never stored in the repo. Supply it as Gradle
 * properties, either in `~/.gradle/gradle.properties` (recommended - outside the
 * project, never committed) or on the command line:
 *
 *     ./gradlew :app:bundleRelease \
 *       -PZBR_COURIER_UPLOAD_STORE_FILE=/absolute/path/to/zbr-upload.keystore \
 *       -PZBR_COURIER_UPLOAD_STORE_PASSWORD=... \
 *       -PZBR_COURIER_UPLOAD_KEY_ALIAS=zbr-upload \
 *       -PZBR_COURIER_UPLOAD_KEY_PASSWORD=...
 *
 * When those properties are absent the release build falls back to the debug
 * keystore so that a local smoke-test build still works, and prints a loud
 * warning. Never upload the output of such a build.
 *
 * WHY THE NAMES CARRY "COURIER". `~/.gradle/gradle.properties` is global to the
 * machine, shared by every Gradle project on it - and the ZBR customer app is
 * built on the same machines as this one. Both apps using `ZBR_UPLOAD_*` means
 * one file holding each key twice, and a properties file resolves a duplicate
 * key to the LAST occurrence, silently and per key. That produced a build
 * carrying this app's keystore path with the customer app's store password, and
 * failed as:
 *
 *     Failed to read key zbr-upload from store "...\zbr-upload.keystore":
 *     keystore password was incorrect
 *
 * which names the keystore and so points nowhere near the real cause. The two
 * apps also cannot share one key in the first place: Play pins an app's upload
 * key at its first upload, so each needs its own, and the property names have to
 * keep them apart.
 *
 * The old `ZBR_UPLOAD_*` names are still honoured, with a warning, so an
 * existing setup keeps building rather than silently dropping to the debug
 * keystore - the one failure here that produces an artifact instead of an error.
 */

const { withAppBuildGradle } = require('expo/config-plugins');

const SIGNING_CONFIGS_ANCHOR = 'signingConfigs {';

const RELEASE_SIGNING_CONFIG = `
        release {
            // Read all four from one prefix. Mixing prefixes is how this app's
            // keystore ended up paired with the customer app's password.
            def zbrPrefix = null
            if (project.hasProperty('ZBR_COURIER_UPLOAD_STORE_FILE')) {
                zbrPrefix = 'ZBR_COURIER_UPLOAD_'
            } else if (project.hasProperty('ZBR_UPLOAD_STORE_FILE')) {
                zbrPrefix = 'ZBR_UPLOAD_'
                logger.warn('[ZBR] Using the legacy ZBR_UPLOAD_* properties. Rename them to ZBR_COURIER_UPLOAD_* in ~/.gradle/gradle.properties: that file is shared with the ZBR customer app, and a duplicated key silently resolves to whichever copy comes last.')
            }

            if (zbrPrefix != null) {
                def zbrRequired = ['STORE_FILE', 'STORE_PASSWORD', 'KEY_ALIAS', 'KEY_PASSWORD']
                def zbrMissing = zbrRequired.findAll { !project.hasProperty(zbrPrefix + it) }
                if (!zbrMissing.isEmpty()) {
                    // Failing here beats failing in signReleaseBundle, which is
                    // ten minutes of compilation later.
                    throw new GradleException('[ZBR] Incomplete signing configuration: ' + zbrMissing.collect { zbrPrefix + it }.join(', ') + ' not set. See docs/ANDROID_RELEASE.md section 2.4.')
                }
                storeFile file(project.property(zbrPrefix + 'STORE_FILE').toString())
                storePassword project.property(zbrPrefix + 'STORE_PASSWORD').toString()
                keyAlias project.property(zbrPrefix + 'KEY_ALIAS').toString()
                keyPassword project.property(zbrPrefix + 'KEY_PASSWORD').toString()
            } else {
                logger.warn('[ZBR] ZBR_COURIER_UPLOAD_STORE_FILE is not set - the release build will be signed with the DEBUG keystore. Google Play will reject this artifact.')
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }`;

// The exact lines the bare template emits for the release build type.
const TEMPLATE_RELEASE_SIGNING = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const PATCHED_RELEASE_SIGNING = `            // Signed by withAndroidReleaseSigning: reads ZBR_UPLOAD_* Gradle properties.
            signingConfig signingConfigs.release`;

/** @type {import('expo/config-plugins').ConfigPlugin} */
const withAndroidReleaseSigning = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `withAndroidReleaseSigning expected a Groovy build.gradle, got "${cfg.modResults.language}".`
      );
    }

    let contents = cfg.modResults.contents;

    if (contents.includes('signingConfigs.release')) {
      // Already patched (e.g. prebuild ran twice without --clean).
      return cfg;
    }

    const anchorIndex = contents.indexOf(SIGNING_CONFIGS_ANCHOR);
    if (anchorIndex === -1) {
      throw new Error(
        `withAndroidReleaseSigning could not find "${SIGNING_CONFIGS_ANCHOR}" in android/app/build.gradle. ` +
          'The Expo template changed - update this plugin before releasing, or the AAB will be debug-signed.'
      );
    }

    const insertAt = anchorIndex + SIGNING_CONFIGS_ANCHOR.length;
    contents = contents.slice(0, insertAt) + RELEASE_SIGNING_CONFIG + contents.slice(insertAt);

    if (!contents.includes(TEMPLATE_RELEASE_SIGNING)) {
      throw new Error(
        'withAndroidReleaseSigning could not find the template release signingConfig line in ' +
          'android/app/build.gradle. The Expo template changed - update this plugin before ' +
          'releasing, or the AAB will be debug-signed.'
      );
    }
    contents = contents.replace(TEMPLATE_RELEASE_SIGNING, PATCHED_RELEASE_SIGNING);

    cfg.modResults.contents = contents;
    return cfg;
  });

module.exports = withAndroidReleaseSigning;
